"""engine_v2 delisting-exit hook tests (Norgate plan Phase N0 / N1 prereg policy).

Policy under test (plan what-can-we-do-squishy-iverson.md, N1_PREREG.md):
positions in names that stop trading EXIT AT LAST QUOTED CLOSE (zipline-
norgatedata auto_close_date convention), opt-in via
``BTConfigV2(delist_exit=True)`` + ``run_backtest_v2(..., last_quote=...)``;
sensitivity arm ``delist_haircut_pct`` applies an extra -haircut one-day
return on the exit day for bankruptcy-class names (terminal adjusted close
< 20% of the close 252 trading days earlier).

Pre-hook silent behavior (engine_v2.run_backtest_v2, documented here because
test (a) freezes it): after a symbol's last quote its closes are NaN, so
``prices.pct_change(fill_method=None).fillna(0.0)`` yields exactly 0.0/day;
the ffilled decision weight persists, so the dead position earns zero
forever while still counting in ``_clip_and_cap`` gross (deflating live
names when the leverage cap binds) and in margin/borrow notionals. No exit
trade or tc is ever charged unless a later decision changes the weight (a
phantom-price trade with zero P&L).

Tests:
  (a) default off  : byte-identical to the PRE-CHANGE engine (pristine output
                     captured before the edit, embedded below as base64
                     pickle); passing ``last_quote`` with delist_exit=False
                     is byte-identical to not passing it; the silent dead-
                     name behavior above is pinned.
  (b) hook on      : position exits at last quoted close, tc charged on the
                     exit turnover, gross frees up (cap no longer deflated by
                     the dead name), subsequent returns provably unaffected
                     by the dead name (garbage post-death prices change
                     nothing); equivalent to manually zeroing the weights.
  (c) haircut arm  : the extra -30% hits exactly the bankruptcy-class name's
                     exit day and NOT the acquisition-class name's.
  (d) fidelity     : validation/test_engine_v2.py run as a script must print
                     ALL TESTS PASSED (published-record chain intact).

Run:  cd "Traiding 11" && /opt/anaconda3/bin/python validation/test_delisting_hook.py
(plain script, no pytest dependency; exits non-zero on failure)
"""
from __future__ import annotations

import base64
import pickle
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from engine_v2 import BTConfigV2, expand_daily, run_backtest_v2  # noqa: E402

FAILURES: list[str] = []


def check(label: str, cond: bool, detail: str = ""):
    flag = "OK  " if cond else "FAIL"
    print(f"  {flag} {label} {detail}")
    if not cond:
        FAILURES.append(label)
    assert cond, f"{label} {detail}".strip()


# ───── synthetic panel: one bankruptcy, one acquisition, two survivors ────
N_DAYS = 300
BANKR_LAST = 270   # index position of BANKR's last quoted day
ACQ_LAST = 280     # index position of ACQ's last quoted day


def build_panel():
    """4-name close/open panel + sparse weights + last_quote series.

    BANKR : log-linear collapse 100 → 4 over 271 quoted days; terminal 4 is
            ~5% of its close 252 trading days earlier (~80.7) → bankruptcy
            class under the prereg's <20% rule.
    ACQ   : log-linear rise 100 → 130 over 281 quoted days; terminal 130 is
            ~127% of its 252d-ago close (~102.6) → NOT bankruptcy class.
    Both go NaN after their last quoted day (the documented Norgate export
    behavior: series simply end).
    Weights: 0.6 in each of the 4 names decided on day 0 and re-asserted on
    day 285 (AFTER both deaths — a naive selector re-picking dead names, so
    the hook must override re-assignment too). Gross 2.4 > cap 2.0 → the cap
    binds at 5/6 while all four are alive (effective 0.5 each).
    """
    idx = pd.bdate_range("2023-01-02", periods=N_DAYS)

    def walk(start, drift, vol, seed):
        r = np.random.RandomState(seed).normal(drift, vol, N_DAYS)
        r[0] = 0.0
        return start * np.exp(np.cumsum(r))

    close = pd.DataFrame(
        {"LIVE1": walk(100.0, 4e-4, 0.010, 1),
         "LIVE2": walk(80.0, 2e-4, 0.012, 2),
         "BANKR": np.nan, "ACQ": np.nan},
        index=idx,
    )
    close.iloc[: BANKR_LAST + 1, close.columns.get_loc("BANKR")] = np.exp(
        np.linspace(np.log(100.0), np.log(4.0), BANKR_LAST + 1))
    close.iloc[: ACQ_LAST + 1, close.columns.get_loc("ACQ")] = np.exp(
        np.linspace(np.log(100.0), np.log(130.0), ACQ_LAST + 1))

    opn = (close.shift(1) + close) / 2.0
    opn.iloc[0] = close.iloc[0] * 0.999

    w = pd.DataFrame([[0.6] * 4, [0.6] * 4],
                     index=[idx[0], idx[285]], columns=close.columns)
    last_quote = pd.Series({"BANKR": idx[BANKR_LAST], "ACQ": idx[ACQ_LAST]})
    return idx, close, opn, w, last_quote


# Pristine engine output on build_panel(), captured with the PRE-CHANGE
# engine_v2 (commit-time state, BEFORE the delisting hook was added) via
# scratchpad capture_pristine.py: base64(pickle({model: {returns, equity,
# summary-subset}})). Regenerating requires the pre-change engine; the blob
# IS the frozen reference.
PRISTINE_B64 = (  # captured 2026-07-29 from the pre-change engine
    "gASV/lsAAAAAAAB9lCiMCW5leHRfb3BlbpR9lCiMB3JldHVybnOUjBJwYW5kYXMuY29yZS5zZXJpZXOUjAZTZXJpZXOUk5Qp"
    "gZR9lCiMBF9tZ3KUjB5wYW5kYXMuY29yZS5pbnRlcm5hbHMubWFuYWdlcnOUjBJTaW5nbGVCbG9ja01hbmFnZXKUk5QpgZQo"
    "XZSMHXBhbmRhcy5jb3JlLmluZGV4ZXMuZGF0ZXRpbWVzlIwSX25ld19EYXRldGltZUluZGV4lJOUaA+MDURhdGV0aW1lSW5k"
    "ZXiUk5R9lCiMBGRhdGGUjBNwYW5kYXMuX2xpYnMuYXJyYXlzlIwcX19weXhfdW5waWNrbGVfTkRBcnJheUJhY2tlZJSTlIwc"
    "cGFuZGFzLmNvcmUuYXJyYXlzLmRhdGV0aW1lc5SMDURhdGV0aW1lQXJyYXmUk5RKHwbxBE6HlFKUjAVudW1weZSMBWR0eXBl"
    "lJOUjAJNOJSJiIeUUpQoSwSMATyUTk5OSv////9K/////0sAfZQoQwJuc5RLAUsBSwF0lIaUdJRijBZudW1weS5fY29yZS5t"
    "dWx0aWFycmF5lIwMX3JlY29uc3RydWN0lJOUaB6MB25kYXJyYXmUk5RLAIWUQwFilIeUUpQoSwFNLAGFlGggjAJNOJSJiIeU"
    "UpQoSwRoJE5OTkr/////Sv////9LAH2UKEMCbnOUSwFLAUsBdJSGlHSUYolCYAkAAAAAEWXYVDYXAABg9myjNhcAAK+HAfI2"
    "FwAA/hiWQDcXAABNqiqPNxcAADpe6Ho4FwAAie98yTgXAADYgBEYORcAACcSpmY5FwAAdqM6tTkXAABjV/igOhcAALLojO86"
    "FwAAAXohPjsXAABQC7aMOxcAAJ+cSts7FwAAjFAIxzwXAADb4ZwVPRcAACpzMWQ9FwAAeQTGsj0XAADIlVoBPhcAALVJGO0+"
    "FwAABNusOz8XAABTbEGKPxcAAKL91dg/FwAA8Y5qJ0AXAADeQigTQRcAAC3UvGFBFwAAfGVRsEEXAADL9uX+QRcAABqIek1C"
    "FwAABzw4OUMXAABWzcyHQxcAAKVeYdZDFwAA9O/1JEQXAABDgYpzRBcAADA1SF9FFwAAf8bcrUUXAADOV3H8RRcAAB3pBUtG"
    "FwAAbHqamUYXAABZLliFRxcAAKi/7NNHFwAA91CBIkgXAABG4hVxSBcAAJVzqr9IFwAAgidoq0kXAADRuPz5SRcAACBKkUhK"
    "FwAAb9sll0oXAAC+bLrlShcAAKsgeNFLFwAA+rEMIEwXAABJQ6FuTBcAAJjUNb1MFwAA52XKC00XAADUGYj3TRcAACOrHEZO"
    "FwAAcjyxlE4XAADBzUXjThcAABBf2jFPFwAA/RKYHVAXAABMpCxsUBcAAJs1wbpQFwAA6sZVCVEXAAA5WOpXURcAACYMqENS"
    "FwAAdZ08klIXAADELtHgUhcAABPAZS9TFwAAYlH6fVMXAABPBbhpVBcAAJ6WTLhUFwAA7SfhBlUXAAA8uXVVVRcAAItKCqRV"
    "FwAAeP7Hj1YXAADHj1zeVhcAABYh8SxXFwAAZbKFe1cXAAC0QxrKVxcAAKH317VYFwAA8IhsBFkXAAA/GgFTWRcAAI6rlaFZ"
    "FwAA3Twq8FkXAADK8OfbWhcAABmCfCpbFwAAaBMReVsXAAC3pKXHWxcAAAY2OhZcFwAA8+n3AV0XAABCe4xQXRcAAJEMIZ9d"
    "FwAA4J217V0XAAAvL0o8XhcAABzjByhfFwAAa3Scdl8XAAC6BTHFXxcAAAmXxRNgFwAAWChaYmAXAABF3BdOYRcAAJRtrJxh"
    "FwAA4/5A62EXAAAykNU5YhcAAIEhaohiFwAAbtUndGMXAAC9ZrzCYxcAAAz4UBFkFwAAW4nlX2QXAACqGnquZBcAAJfON5pl"
    "FwAA5l/M6GUXAAA18WA3ZhcAAISC9YVmFwAA0xOK1GYXAADAx0fAZxcAAA9Z3A5oFwAAXupwXWgXAACtewWsaBcAAPwMmvpo"
    "FwAA6cBX5mkXAAA4Uuw0ahcAAIfjgINqFwAA1nQV0moXAAAlBqogaxcAABK6ZwxsFwAAYUv8WmwXAACw3JCpbBcAAP9tJfhs"
    "FwAATv+5Rm0XAAA7s3cybhcAAIpEDIFuFwAA2dWgz24XAAAoZzUebxcAAHf4yWxvFwAAZKyHWHAXAACzPRyncBcAAALPsPVw"
    "FwAAUWBFRHEXAACg8dmScRcAAI2ll35yFwAA3DYszXIXAAAryMAbcxcAAHpZVWpzFwAAyerpuHMXAAC2nqekdBcAAAUwPPN0"
    "FwAAVMHQQXUXAACjUmWQdRcAAPLj+d51FwAA35e3ynYXAAAuKUwZdxcAAH264Gd3FwAAzEt1tncXAAAb3QkFeBcAAAiRx/B4"
    "FwAAVyJcP3kXAACms/CNeRcAAPVEhdx5FwAARNYZK3oXAAAxitcWexcAAIAbbGV7FwAAz6wAtHsXAAAePpUCfBcAAG3PKVF8"
    "FwAAWoPnPH0XAACpFHyLfRcAAPilENp9FwAARzelKH4XAACWyDl3fhcAAIN892J/FwAA0g2MsX8XAAAhnyAAgBcAAHAwtU6A"
    "FwAAv8FJnYAXAACsdQeJgRcAAPsGnNeBFwAASpgwJoIXAACZKcV0ghcAAOi6WcOCFwAA1W4Xr4MXAAAkAKz9gxcAAHORQEyE"
    "FwAAwiLVmoQXAAARtGnphBcAAP5nJ9WFFwAATfm7I4YXAACcilByhhcAAOsb5cCGFwAAOq15D4cXAAAnYTf7hxcAAHbyy0mI"
    "FwAAxYNgmIgXAAAUFfXmiBcAAGOmiTWJFwAAUFpHIYoXAACf69tvihcAAO58cL6KFwAAPQ4FDYsXAACMn5lbixcAAHlTV0eM"
    "FwAAyOTrlYwXAAAXdoDkjBcAAGYHFTONFwAAtZipgY0XAACiTGdtjhcAAPHd+7uOFwAAQG+QCo8XAACPACVZjxcAAN6RuaeP"
    "FwAAy0V3k5AXAAAa1wvikBcAAGlooDCRFwAAuPk0f5EXAAAHi8nNkRcAAPQ+h7mSFwAAQ9AbCJMXAACSYbBWkxcAAOHyRKWT"
    "FwAAMITZ85MXAAAdOJfflBcAAGzJKy6VFwAAu1rAfJUXAAAK7FTLlRcAAFl96RmWFwAARjGnBZcXAACVwjtUlxcAAORT0KKX"
    "FwAAM+Vk8ZcXAACCdvk/mBcAAG8qtyuZFwAAvrtLepkXAAANTeDImRcAAFzedBeaFwAAq28JZpoXAACYI8dRmxcAAOe0W6Cb"
    "FwAANkbw7psXAACF14Q9nBcAANRoGYycFwAAwRzXd50XAAAQrmvGnRcAAF8/ABWeFwAArtCUY54XAAD9YSmynhcAAOoV552f"
    "FwAAOad77J8XAACIOBA7oBcAANfJpImgFwAAJls52KAXAAATD/fDoRcAAGKgixKiFwAAsTEgYaIXAAAAw7SvohcAAE9USf6i"
    "FwAAPAgH6qMXAACLmZs4pBcAANoqMIekFwAAKbzE1aQXAAB4TVkkpRcAAGUBFxCmFwAAtJKrXqYXAAADJECtphcAAFK11Pum"
    "FwAAoUZpSqcXAACO+iY2qBcAAN2Lu4SoFwAALB1Q06gXAAB7ruQhqRcAAMo/eXCpFwAAt/M2XKoXAAAGhcuqqhcAAFUWYPmq"
    "FwAApKf0R6sXAADzOImWqxcAAODsRoKsFwAAL37b0KwXAAB+D3AfrRcAAM2gBG6tFwAAHDKZvK0XAAAJ5laorhcAAFh36/au"
    "FwAApwiARa8XAAD2mRSUrxcAAEUrqeKvFwAAMt9mzrAXAACBcPscsRcAANABkGuxFwAAH5MkurEXAABuJLkIshcAAFvYdvSy"
    "FwAAqmkLQ7MXAAD5+p+RsxcAAEiMNOCzFwAAlx3JLrQXAACE0YYatRcAANNiG2m1FwAAIvSvt7UXAABxhUQGthcAAMAW2VS2"
    "F5R0lGJ9lCiMBV9mcmVxlIwbcGFuZGFzLl9saWJzLnRzbGlicy5vZmZzZXRzlIwLQnVzaW5lc3NEYXmUk5RLAYmMCGRhdGV0"
    "aW1llIwJdGltZWRlbHRhlJOUSwBLAEsAh5RSlIeUUpSMBl9jYWNoZZR9lCiMBl9jcmVzb5RLCowEdW5pdJSMAm5zlHV1h5Ri"
    "jARuYW1llE51hpRSlGFdlGgsaC5LAIWUaDCHlFKUKEsBTSwBhZRoIIwCZjiUiYiHlFKUKEsDaCROTk5K/////0r/////SwB0"
    "lGKJQmAJAAAAAAAAAAAAAL9RJ1WEr3W/MJZjpnLwlL8AVvf2eCZCv+DlPwO8doe/4PUFQcUUlr/AV2eTp1Z7P8BUaMuiwpC/"
    "IFK0wT41hL9A7Ox2RzmIv8DOUkCBp3Y/ANNJwIcWV7+AaYGaF7J6v+CmYQnBIoy/gBx3ELoQbz8gBYu/SRGNvwDt4UctH3m/"
    "gJh3ziniY7/gJtOAakeDvwBTCPNC2WG/AD5epzxBkL8AyCNrFwI2vwDav78YAE4/gLkKGSt7gb+ASOxQV8llv2Cfu16fcIS/"
    "gHNFIVGgg78QPsY7LUyRvyB2GQjwno6/AKrbP0D+a78g54yaZuyEv8AcT1/8Wno/oAqqYqyIl78gnXnd4suBv0CayazLs3m/"
    "gB2Obq2gaD+ASgqBSIN/v8Done/qeoK/gKcFDkNWaj8Aii1QGg1eP0BxhTTDXoC/gJ1mY+0vdL+wNVCeAHKUv2BStH6CbIw/"
    "gJgVF9ZQcD+ARAP+1y6FvwCybCMa/kC/gFnuNgiLdz+ADCFKHniDvwCSghgCH1m/gBe1kv+MYz/AvE99ENaCvyBjE1Ufzoq/"
    "wOWyjbcYfr8A0+9Ndm1tvwDSaoAomXY/AHCVD+5mc78AuvIXXShlP4Azxzbj4mO/oN/oQCcLiL8A172MkGaHvwAI/lqaVTc/"
    "gPtt3N0dZ7+AjjMm5zBzv6D7ACH4UI6/QG4mE0aIdb+AeEpIgMpsvwBr2AMd03i/YHM6S/aJgj/AvH92g2F/vxDiDyxxn5C/"
    "gMVJ+XU8Zb8Aq6PlbTJ7vwAMvlZuTze/wF8fbeG8hL8Ay+bC9tB2v9APnfdt7pa/ALSzmY1WWb8AoI69TjAoP4BTG5Uvaou/"
    "wDzOAPBSfr8AVxd1zyB7vwBaYJPTnEg/wPdSpLA1cj/AsCNuhvV6vwBfhTuFN4q/APBmg5XOLb8ACN0M78hwP4ApoOgW832/"
    "gKvT5mGWZT+Adf5W2/5pPwCWuJL13Eq/QNpOdkfFd78AYLBhU40mP4DNHaxAWou/ADgnEB7VWD+AfPv778dyv8DYbBcVj3m/"
    "ALRORGHwUr/gNqMttcmPvwDEaJ+bLTi/AFHvUdFDaz8gieS9bECEvwCAhZh//Ds/gKQI8Vpyib/AO6v1unKHP8AvnRBh3IM/"
    "QKvQ1hW1fb8gHM7ZHhaGvwBERwRHX4G/IN18G7WEjL+AarxlKmF8vwDT7Nc7xXm/QMSgrdiQir9Amu06arR0v6BMET7WP46/"
    "4PwyO+OBg7/gOnXSpSqTv3BoWIJAaZA/oI8AOnhPiL9Am1TVRUqHv0AJINwtSXq/AD7B3zhfRr8AwPx9JQZ+P6BAYBiNjIO/"
    "AI/5rDnRgT8ATUN79BB/P2BejxbUO4O/QG36XZgZcr9gDc6XWySHvwD7iO/Lonu/QFOg71zVhr/gpQAPFAWSvwBe1f0BI1M/"
    "ALV2Ea2gYr+AZpzUskRhv4C6XKn1RYe/wColIU6Gd78AhYra4ZheP8C62Z8+DnG/gHbEkbjCjb/Av31KimJ9vyAD5+2JdIS/"
    "YM197dAfjL8w3vBpzf6RPwAF1nRy0lY/QO1ZV5kDeT/AUi2UfO5yvwDApYT+nio/gDTG1SBAZD8ADFCIwkBpv/C7iSoolJG/"
    "AMhMfxpSVb9AY4y/SBF6vwCAO0lI80c/gPOuTQ15ab8AklAOj/xNP8BSgycpSn6/APjlYTGAdj/AGJio3HmLv6ABVi6YKI+/"
    "QLOxQqdBcr/AQOGRiX97v+D6q1Kd5oy/ABgElEqFX78A7MVaYBJYvwDsPb/YhFQ/AAZs6gnqUb+QpzfRI/KfP0B6eqyeqYO/"
    "AEqU7fZVTT/AxRFyGGeJvwB14/KKKoQ/AEFflJdfXL/A3mSnqip9v4Cd5aQlloe/QBMk4xYccD+gJmnyA1yBv8AbRhcnr3W/"
    "ABjJBAw3KT+A8U2A095rvwCLj2YB8Vy/wIJWRenrdb8ABh0vlTpyPwDMy8OOJEe/gL7AU+crcr/gK4ERxHyGv4AulsLDeXi/"
    "ALmfSAURWr8AAtdMuBFdv8B9qqMai3o/AOJ5rmXBVD+AKy5bTdZiv4AsFSAAGG+/wLrkxpGwgr+AkiRQObZivwDm8DAYOFG/"
    "AOhhJ5tkMj9A3ATrhhx1PwBnofSiul6/gMJPM161jL8AQhcALEFtv2CVyVzQH4K/oPUdIlpIjD+AkbN7KL56v+ARaKte25S/"
    "wBbScNYig7/AvyXOiiR1v+DLMSwvdpG/wAVm1vaucD+g2HiEKDKSv6BGFr9SJ4S/AKGDsqWhV78gBuqIT4GQv+BbRFLHso+/"
    "AMwVvcV2Rj+AXUPRgdt1vwBn5F5co3a/gDwE3dKMdT+A1k1T3IODvwAWlsn4dFI/YIyJwqdNhT+AeuRdxhZsP+Bj48l4y4O/"
    "4M44PqI8hr8ACAy/Fq5HvwC6T/wR9VC/AEkxVKkRcL+A0+yCIh1hvwBEsv9d50e/ALKYGVEcWr8ASasfhoxcPwAghR48jka/"
    "AMBTgwdOEr/gZSA2+kuIv6DFMYjsm4y/gK6z19l3mr8ATqbimVNlP1AorTfMNZi/AO1KyV0gWL8AceOR2bePvxDmLxcmK5O/"
    "AJnKymoud78g3s0bm4GMv0AYQFvDToW/AAColn4lWT8AC9oZyY13v8D/fflq2XS/QI1TXTX3fD9gbPkCBvWLvwCPhodOkYG/"
    "ACyrn+Aiab+wObh0cgmTv0Du5nU74HY/EMTDJTfJkb+gQdg7lHyEv8DjjP8anX4/ABYTmoDUaL8AnWt+2h1Qv4BQaDDVqGs/"
    "gGvT9lLYcL9A6+Z2jtyBv0DcebZIjnm/YHtoldTPiL/AQ0GcYSN+vwDypqGsQXW/gHrTW9Hubr8Av/HpJEiDv0B8ZPEDv3O/"
    "8JloVkjHkb/AU5LINxGGvwD8/dg8eXI/AIr/Mg07Xb8AZaIMj31VP8CNZdSzvH2/QEiRKXQrd78A0NNeDC4Tv8CfndOcPY8/"
    "gB2pMwW2bz8Ay44CtDZ3PwAJSHYCUng/gEQQ0fqAhr/AcwCF4PmGvwBPGz/vyno/AJzo08RbQz8AsvccyBpBPwBMQmBG8kI/"
    "4E7U4OmIgb+A2KuglOCIv0A93tM7uYA/QITYkRbXdj9AVCo1TJpxvwBDBdIktY0/4NNBQ0Bpg7+ATOOeWP9svwDahwytxUI/"
    "ANuX4zFec78ArmZ98qVVPwBVZjGngHa/ACYdvJSWTD+UdJRiYV2UaBFoE32UKGgVaBhoG0ofBvEEToeUUpRoI2gsaC5LAIWU"
    "aDCHlFKUKEsBTSwBhZRoNolCYAkAAAAAEWXYVDYXAABg9myjNhcAAK+HAfI2FwAA/hiWQDcXAABNqiqPNxcAADpe6Ho4FwAA"
    "ie98yTgXAADYgBEYORcAACcSpmY5FwAAdqM6tTkXAABjV/igOhcAALLojO86FwAAAXohPjsXAABQC7aMOxcAAJ+cSts7FwAA"
    "jFAIxzwXAADb4ZwVPRcAACpzMWQ9FwAAeQTGsj0XAADIlVoBPhcAALVJGO0+FwAABNusOz8XAABTbEGKPxcAAKL91dg/FwAA"
    "8Y5qJ0AXAADeQigTQRcAAC3UvGFBFwAAfGVRsEEXAADL9uX+QRcAABqIek1CFwAABzw4OUMXAABWzcyHQxcAAKVeYdZDFwAA"
    "9O/1JEQXAABDgYpzRBcAADA1SF9FFwAAf8bcrUUXAADOV3H8RRcAAB3pBUtGFwAAbHqamUYXAABZLliFRxcAAKi/7NNHFwAA"
    "91CBIkgXAABG4hVxSBcAAJVzqr9IFwAAgidoq0kXAADRuPz5SRcAACBKkUhKFwAAb9sll0oXAAC+bLrlShcAAKsgeNFLFwAA"
    "+rEMIEwXAABJQ6FuTBcAAJjUNb1MFwAA52XKC00XAADUGYj3TRcAACOrHEZOFwAAcjyxlE4XAADBzUXjThcAABBf2jFPFwAA"
    "/RKYHVAXAABMpCxsUBcAAJs1wbpQFwAA6sZVCVEXAAA5WOpXURcAACYMqENSFwAAdZ08klIXAADELtHgUhcAABPAZS9TFwAA"
    "YlH6fVMXAABPBbhpVBcAAJ6WTLhUFwAA7SfhBlUXAAA8uXVVVRcAAItKCqRVFwAAeP7Hj1YXAADHj1zeVhcAABYh8SxXFwAA"
    "ZbKFe1cXAAC0QxrKVxcAAKH317VYFwAA8IhsBFkXAAA/GgFTWRcAAI6rlaFZFwAA3Twq8FkXAADK8OfbWhcAABmCfCpbFwAA"
    "aBMReVsXAAC3pKXHWxcAAAY2OhZcFwAA8+n3AV0XAABCe4xQXRcAAJEMIZ9dFwAA4J217V0XAAAvL0o8XhcAABzjByhfFwAA"
    "a3Scdl8XAAC6BTHFXxcAAAmXxRNgFwAAWChaYmAXAABF3BdOYRcAAJRtrJxhFwAA4/5A62EXAAAykNU5YhcAAIEhaohiFwAA"
    "btUndGMXAAC9ZrzCYxcAAAz4UBFkFwAAW4nlX2QXAACqGnquZBcAAJfON5plFwAA5l/M6GUXAAA18WA3ZhcAAISC9YVmFwAA"
    "0xOK1GYXAADAx0fAZxcAAA9Z3A5oFwAAXupwXWgXAACtewWsaBcAAPwMmvpoFwAA6cBX5mkXAAA4Uuw0ahcAAIfjgINqFwAA"
    "1nQV0moXAAAlBqogaxcAABK6ZwxsFwAAYUv8WmwXAACw3JCpbBcAAP9tJfhsFwAATv+5Rm0XAAA7s3cybhcAAIpEDIFuFwAA"
    "2dWgz24XAAAoZzUebxcAAHf4yWxvFwAAZKyHWHAXAACzPRyncBcAAALPsPVwFwAAUWBFRHEXAACg8dmScRcAAI2ll35yFwAA"
    "3DYszXIXAAAryMAbcxcAAHpZVWpzFwAAyerpuHMXAAC2nqekdBcAAAUwPPN0FwAAVMHQQXUXAACjUmWQdRcAAPLj+d51FwAA"
    "35e3ynYXAAAuKUwZdxcAAH264Gd3FwAAzEt1tncXAAAb3QkFeBcAAAiRx/B4FwAAVyJcP3kXAACms/CNeRcAAPVEhdx5FwAA"
    "RNYZK3oXAAAxitcWexcAAIAbbGV7FwAAz6wAtHsXAAAePpUCfBcAAG3PKVF8FwAAWoPnPH0XAACpFHyLfRcAAPilENp9FwAA"
    "RzelKH4XAACWyDl3fhcAAIN892J/FwAA0g2MsX8XAAAhnyAAgBcAAHAwtU6AFwAAv8FJnYAXAACsdQeJgRcAAPsGnNeBFwAA"
    "SpgwJoIXAACZKcV0ghcAAOi6WcOCFwAA1W4Xr4MXAAAkAKz9gxcAAHORQEyEFwAAwiLVmoQXAAARtGnphBcAAP5nJ9WFFwAA"
    "Tfm7I4YXAACcilByhhcAAOsb5cCGFwAAOq15D4cXAAAnYTf7hxcAAHbyy0mIFwAAxYNgmIgXAAAUFfXmiBcAAGOmiTWJFwAA"
    "UFpHIYoXAACf69tvihcAAO58cL6KFwAAPQ4FDYsXAACMn5lbixcAAHlTV0eMFwAAyOTrlYwXAAAXdoDkjBcAAGYHFTONFwAA"
    "tZipgY0XAACiTGdtjhcAAPHd+7uOFwAAQG+QCo8XAACPACVZjxcAAN6RuaePFwAAy0V3k5AXAAAa1wvikBcAAGlooDCRFwAA"
    "uPk0f5EXAAAHi8nNkRcAAPQ+h7mSFwAAQ9AbCJMXAACSYbBWkxcAAOHyRKWTFwAAMITZ85MXAAAdOJfflBcAAGzJKy6VFwAA"
    "u1rAfJUXAAAK7FTLlRcAAFl96RmWFwAARjGnBZcXAACVwjtUlxcAAORT0KKXFwAAM+Vk8ZcXAACCdvk/mBcAAG8qtyuZFwAA"
    "vrtLepkXAAANTeDImRcAAFzedBeaFwAAq28JZpoXAACYI8dRmxcAAOe0W6CbFwAANkbw7psXAACF14Q9nBcAANRoGYycFwAA"
    "wRzXd50XAAAQrmvGnRcAAF8/ABWeFwAArtCUY54XAAD9YSmynhcAAOoV552fFwAAOad77J8XAACIOBA7oBcAANfJpImgFwAA"
    "Jls52KAXAAATD/fDoRcAAGKgixKiFwAAsTEgYaIXAAAAw7SvohcAAE9USf6iFwAAPAgH6qMXAACLmZs4pBcAANoqMIekFwAA"
    "KbzE1aQXAAB4TVkkpRcAAGUBFxCmFwAAtJKrXqYXAAADJECtphcAAFK11PumFwAAoUZpSqcXAACO+iY2qBcAAN2Lu4SoFwAA"
    "LB1Q06gXAAB7ruQhqRcAAMo/eXCpFwAAt/M2XKoXAAAGhcuqqhcAAFUWYPmqFwAApKf0R6sXAADzOImWqxcAAODsRoKsFwAA"
    "L37b0KwXAAB+D3AfrRcAAM2gBG6tFwAAHDKZvK0XAAAJ5laorhcAAFh36/auFwAApwiARa8XAAD2mRSUrxcAAEUrqeKvFwAA"
    "Mt9mzrAXAACBcPscsRcAANABkGuxFwAAH5MkurEXAABuJLkIshcAAFvYdvSyFwAAqmkLQ7MXAAD5+p+RsxcAAEiMNOCzFwAA"
    "lx3JLrQXAACE0YYatRcAANNiG2m1FwAAIvSvt7UXAABxhUQGthcAAMAW2VS2F5R0lGJ9lGg/aEJLAYloR4eUUpRzh5RiaFBO"
    "dYaUUpRhfZSMBjAuMTQuMZR9lCiMBGF4ZXOUaA6MBmJsb2Nrc5RdlH2UKIwGdmFsdWVzlGhWjAhtZ3JfbG9jc5SMCGJ1aWx0"
    "aW5zlIwFc2xpY2WUk5RLAE0sAUsBh5RSlHVhdXN0lGKMBF90eXCUjAZzZXJpZXOUjAlfbWV0YWRhdGGUXZSMBV9uYW1llGGM"
    "BWF0dHJzlH2UjAZfZmxhZ3OUfZSMF2FsbG93c19kdXBsaWNhdGVfbGFiZWxzlIhzaIFOdWKMBmVxdWl0eZRoBimBlH2UKGgJ"
    "aAwpgZQoXZRoUmFdlGgsaC5LAIWUaDCHlFKUKEsBTSwBhZRoWolCYAkAAAAAAAAAavhA4ZCzDulI+EBvfLqyyMn3QDmzHixp"
    "xvdAV0Bw4K2A90BH87gZ8P72QHaqB9o6JvdA471TgjvF9kBxyEPgtov2QLLfxE5yR/ZAP9+jyf1m9kDjnIPj6F72QLOOMqiV"
    "OfZAXIhij2vr9UAA4L4UswD2QNPuQf/AsPVA0JfajbKO9UA6aN93TYH1QN2eB2Z6TfVAltAJm5hB9UBteVyMN+v0QCgX1ilr"
    "6fRAEv3+4lHu9EA1IA80lcD0QPO22z90svRA87aQvpJ99EBIlsjiTUv0QCh8fluL8/NAEYtIsC2n80Axk0t7/JXzQLVtTMDC"
    "YvNAKVkTerGC80ByJC5Z5w/zQL0qcb1/5fJAnzzIzSTH8kCiFuBymNXyQKxDWBGAsPJAvci1yFOF8kDgTOkJkpTyQII+L3xL"
    "nfJA/qfLZjR38kBCyygV6F/yQHtnkdz8AfJARYgoEvhB8kADuV9IllTyQJ5RmugMJPJA30i/Y6Qh8kA84KFNUjzyQFrFSzzx"
    "D/JALvS/QdoI8kB+Fxv63hPyQJbPmItO6fFArQmGzkqt8UAuBIiTCozxQOgmD6Tne/FAoOOpX5mU8UAV/6LQR3/xQMKvxGnZ"
    "ivFAM2p/l/J/8UAGoO1ZWkvxQN9+7vzDGPFA2UQS7lIa8UB5YwgM+A3xQBqQL1WD+fBAPtsR2y+58EBFWO1crqLwQMsPv762"
    "k/BAlkaXcv558ECrxYATLaDwQNcif2iRf/BABKQ/gQE78EDa0ckdPDDwQLG+arK3FPBANq2W2EAT8EAMGxlaKtPvQKZO5FvI"
    "pe9A4t/MH1rw7kAahStlGuTuQHbsigCQ5e5AQIUQIa977kD1MJA16UHuQEE74e+bDu5AS/KagGMU7kAbbipgnzbuQOtG7Pq2"
    "A+5AGbjVmlqh7UAXb6ECoZ/tQHT3mKm0vu1ACxM3FweH7UBU1yV38prtQNZlZE3/su1AwzjnrMOs7UDSWutvrYDtQGnqHBz6"
    "ge1APqM1ixYd7UBY2iVmYijtQKKn1JsoBu1ABacTb8vX7EDgr8toQs/sQHt5m+PIXOxACPw4Ixta7EA2nzxAQ3LsQMtBWINA"
    "KuxALFvHv1Qt7EDecalQtNPrQNh9KwpEJexAVwkR4iNr7EBbMjcOYDbsQHvxu4N86OtA1yefGuKr60DwU798PUnrQMd/0pzX"
    "GOtACXK1xDLt6kBOjtdYyJPqQLSnZe9jcepABpSKt2cN6kBrExHl4M3pQFFzXdk7UulAydDCDx+66UCYc/4h8WvpQAZXXcju"
    "IelAthh9saT46ECL7IthR/ToQC77dv0aI+lAglmt+63l6EBZQ0QxIR3pQKKccj7kTelAuoMTAw4R6UBk6PS5svToQAIFQc2B"
    "rOhAK1YWpeOB6EDMfw/U8DvoQCGY4VPEzudAy4T7u+LV50CSxxq+AsjnQNFkuW4tu+dAQID4xCN250DcQJEBpVPnQCuY4+/L"
    "XudAH3LJaOJF50AyxWucTu/mQLf2850vxeZA468g8/aK5kBZg5brtjvmQNtroPq8n+ZAK38wSM6n5kDUTBiTOcvmQNlO4DFB"
    "sOZAw0bbMG+x5kBROoGQy7/mQDSKla/XreZA61ID1yxK5kAx2gjov0LmQIwFDWR7HuZA5wyV6J4i5kAfrFIgABHmQGG0e4Qr"
    "FuZA3ayKk1vs5UBZJPw3MAvmQIemAax6v+VAhrKNVcZq5UAh+8NUVlLlQAVGNG6xLeVA+9gJ/y7h5EDL/ftv5tbkQH9Hwd0P"
    "z+RA5lBAxLvV5EA8S6/N5s/kQKap0OYdduVAeEvpVl5B5UACt7JsPUblQJQgZsOvAuVATKDVNaY35UCC3kIsPi7lQFeERuCh"
    "B+VAtcfRPKHJ5EAdHaVcj97kQFPAQ2JGseRAkr9iMDuV5EC6KEqwPpbkQKtKAZFQhORA64UPawl75ECaMgD1+V7kQKBebmQv"
    "duRAWJXaT3xy5EDevbJoQ1vkQF191fUKIuRAsBqerT4D5EDa9aMJGPvjQJZSg7oE8uNAGcrwaRsT5EBDcgUMnhnkQKfUNgfJ"
    "DeRAEvcMokz640C3EQGHoMvjQKbXH0MNwONAGkkX8Ly640DqEUfSJ7zjQDZuOvYx1uNAHM7LtavM40Dis/58noXjQA23G6PF"
    "c+NAjDAry7NH40DYS/0e3YvjQN1YVIkxa+NAfGg2mfAF40Bg0aCmb9jiQFJVnYmIv+JAcfT+lbBt4kA5vsLL54DiQAOE7rG7"
    "LOJA0QmihvL+4UCOEYhzTfjhQBgUqVAnruFAG+DjXBlo4UCeJhtoJ2vhQEZjY8xbU+FAhBftSNg64UDlpMMqDVLhQBKy4c7M"
    "J+FAYltPW78s4UCMmXiIe1rhQCC4Vw63aeFA+XInGqE+4UAu5Kwrsg7hQJbbplSKC+FAZeIZLQYH4UAHbkJb7PXgQFEQiUTa"
    "7OBA/vFwHbHp4EBt99CxyuLgQEJb/f1S6uBAh8LT61fn4EADKwmRCufgQJ2ZrOq0s+BAvErUafp34EDitOUbAQvgQGIiUT6y"
    "FeBArTleeK9o30CicTJU2FzfQMVNJc1/4N5AikSxWohM3kC/02twoiDeQOEEhiFItd1A7yM5xydm3UBYSPjntHHdQKWTzIdc"
    "Rt1AmD8hxjYg3UAwJW4o8VTdQKieIRtw7txAKig57+eu3EBNX9gGYJjcQH+zprVIENxAEUDlZWg43EAeJ6QS7brbQMNZye7p"
    "c9tApV8j1XCo20ChEnHV+pLbQIPv/jkJjNtAXBh+uNij20CNxIUsv4bbQIcAjfJJSdtAVb2QyLQd20BNowM5m8naQMtXifkl"
    "l9pALg/CctJz2kAQ5fhyQFraQEEIC3S8GtpA5reoDoX62UAARQAUDofZQK3VSryjQNlAVMldzctd2UCNlVHlNVLZQEzIKoy2"
    "WtlAql50Gpcr2UCK1FoVJAfZQGTpTxOsBtlA2OqSq2Zo2UC2ZfJUlIHZQGn5ds6VptlAx+DeKJPN2UAVaAHS/YTZQGa0bwCz"
    "O9lAZpdTDvRl2UDsYxdmy2nZQOZRU8QwbdlAh/aZP/Rw2UCCzpXQMDnZQACgMCjB6thAA/eKmdce2UA2md6zs0LZQBgUnTrp"
    "JtlAH8MxzE+E2UBucBzZZUbZQD7GA5F+L9lANJ71IzAz2UBw3nz/rhTZQHE4Q9EqHdlADvmextj52EDkC9rPbP/YQJR0lGJh"
    "XZRoEWgTfZQoaBVoGGgbSh8G8QROh5RSlGgjaCxoLksAhZRoMIeUUpQoSwFNLAGFlGg2iUJgCQAAAAARZdhUNhcAAGD2bKM2"
    "FwAAr4cB8jYXAAD+GJZANxcAAE2qKo83FwAAOl7oejgXAACJ73zJOBcAANiAERg5FwAAJxKmZjkXAAB2ozq1ORcAAGNX+KA6"
    "FwAAsuiM7zoXAAABeiE+OxcAAFALtow7FwAAn5xK2zsXAACMUAjHPBcAANvhnBU9FwAAKnMxZD0XAAB5BMayPRcAAMiVWgE+"
    "FwAAtUkY7T4XAAAE26w7PxcAAFNsQYo/FwAAov3V2D8XAADxjmonQBcAAN5CKBNBFwAALdS8YUEXAAB8ZVGwQRcAAMv25f5B"
    "FwAAGoh6TUIXAAAHPDg5QxcAAFbNzIdDFwAApV5h1kMXAAD07/UkRBcAAEOBinNEFwAAMDVIX0UXAAB/xtytRRcAAM5XcfxF"
    "FwAAHekFS0YXAABsepqZRhcAAFkuWIVHFwAAqL/s00cXAAD3UIEiSBcAAEbiFXFIFwAAlXOqv0gXAACCJ2irSRcAANG4/PlJ"
    "FwAAIEqRSEoXAABv2yWXShcAAL5suuVKFwAAqyB40UsXAAD6sQwgTBcAAElDoW5MFwAAmNQ1vUwXAADnZcoLTRcAANQZiPdN"
    "FwAAI6scRk4XAAByPLGUThcAAMHNReNOFwAAEF/aMU8XAAD9EpgdUBcAAEykLGxQFwAAmzXBulAXAADqxlUJURcAADlY6ldR"
    "FwAAJgyoQ1IXAAB1nTySUhcAAMQu0eBSFwAAE8BlL1MXAABiUfp9UxcAAE8FuGlUFwAAnpZMuFQXAADtJ+EGVRcAADy5dVVV"
    "FwAAi0oKpFUXAAB4/sePVhcAAMePXN5WFwAAFiHxLFcXAABlsoV7VxcAALRDGspXFwAAoffXtVgXAADwiGwEWRcAAD8aAVNZ"
    "FwAAjquVoVkXAADdPCrwWRcAAMrw59taFwAAGYJ8KlsXAABoExF5WxcAALekpcdbFwAABjY6FlwXAADz6fcBXRcAAEJ7jFBd"
    "FwAAkQwhn10XAADgnbXtXRcAAC8vSjxeFwAAHOMHKF8XAABrdJx2XxcAALoFMcVfFwAACZfFE2AXAABYKFpiYBcAAEXcF05h"
    "FwAAlG2snGEXAADj/kDrYRcAADKQ1TliFwAAgSFqiGIXAABu1Sd0YxcAAL1mvMJjFwAADPhQEWQXAABbieVfZBcAAKoaeq5k"
    "FwAAl843mmUXAADmX8zoZRcAADXxYDdmFwAAhIL1hWYXAADTE4rUZhcAAMDHR8BnFwAAD1ncDmgXAABe6nBdaBcAAK17Baxo"
    "FwAA/Aya+mgXAADpwFfmaRcAADhS7DRqFwAAh+OAg2oXAADWdBXSahcAACUGqiBrFwAAErpnDGwXAABhS/xabBcAALDckKls"
    "FwAA/20l+GwXAABO/7lGbRcAADuzdzJuFwAAikQMgW4XAADZ1aDPbhcAAChnNR5vFwAAd/jJbG8XAABkrIdYcBcAALM9HKdw"
    "FwAAAs+w9XAXAABRYEVEcRcAAKDx2ZJxFwAAjaWXfnIXAADcNizNchcAACvIwBtzFwAAellVanMXAADJ6um4cxcAALaep6R0"
    "FwAABTA883QXAABUwdBBdRcAAKNSZZB1FwAA8uP53nUXAADfl7fKdhcAAC4pTBl3FwAAfbrgZ3cXAADMS3W2dxcAABvdCQV4"
    "FwAACJHH8HgXAABXIlw/eRcAAKaz8I15FwAA9USF3HkXAABE1hkrehcAADGK1xZ7FwAAgBtsZXsXAADPrAC0excAAB4+lQJ8"
    "FwAAbc8pUXwXAABag+c8fRcAAKkUfIt9FwAA+KUQ2n0XAABHN6UofhcAAJbIOXd+FwAAg3z3Yn8XAADSDYyxfxcAACGfIACA"
    "FwAAcDC1ToAXAAC/wUmdgBcAAKx1B4mBFwAA+wac14EXAABKmDAmghcAAJkpxXSCFwAA6LpZw4IXAADVbhevgxcAACQArP2D"
    "FwAAc5FATIQXAADCItWahBcAABG0aemEFwAA/mcn1YUXAABN+bsjhhcAAJyKUHKGFwAA6xvlwIYXAAA6rXkPhxcAACdhN/uH"
    "FwAAdvLLSYgXAADFg2CYiBcAABQV9eaIFwAAY6aJNYkXAABQWkchihcAAJ/r22+KFwAA7nxwvooXAAA9DgUNixcAAIyfmVuL"
    "FwAAeVNXR4wXAADI5OuVjBcAABd2gOSMFwAAZgcVM40XAAC1mKmBjRcAAKJMZ22OFwAA8d37u44XAABAb5AKjxcAAI8AJVmP"
    "FwAA3pG5p48XAADLRXeTkBcAABrXC+KQFwAAaWigMJEXAAC4+TR/kRcAAAeLyc2RFwAA9D6HuZIXAABD0BsIkxcAAJJhsFaT"
    "FwAA4fJEpZMXAAAwhNnzkxcAAB04l9+UFwAAbMkrLpUXAAC7WsB8lRcAAArsVMuVFwAAWX3pGZYXAABGMacFlxcAAJXCO1SX"
    "FwAA5FPQopcXAAAz5WTxlxcAAIJ2+T+YFwAAbyq3K5kXAAC+u0t6mRcAAA1N4MiZFwAAXN50F5oXAACrbwlmmhcAAJgjx1Gb"
    "FwAA57RboJsXAAA2RvDumxcAAIXXhD2cFwAA1GgZjJwXAADBHNd3nRcAABCua8adFwAAXz8AFZ4XAACu0JRjnhcAAP1hKbKe"
    "FwAA6hXnnZ8XAAA5p3vsnxcAAIg4EDugFwAA18mkiaAXAAAmWznYoBcAABMP98OhFwAAYqCLEqIXAACxMSBhohcAAADDtK+i"
    "FwAAT1RJ/qIXAAA8CAfqoxcAAIuZmzikFwAA2iowh6QXAAApvMTVpBcAAHhNWSSlFwAAZQEXEKYXAAC0kqtephcAAAMkQK2m"
    "FwAAUrXU+6YXAAChRmlKpxcAAI76JjaoFwAA3Yu7hKgXAAAsHVDTqBcAAHuu5CGpFwAAyj95cKkXAAC38zZcqhcAAAaFy6qq"
    "FwAAVRZg+aoXAACkp/RHqxcAAPM4iZarFwAA4OxGgqwXAAAvftvQrBcAAH4PcB+tFwAAzaAEbq0XAAAcMpm8rRcAAAnmVqiu"
    "FwAAWHfr9q4XAACnCIBFrxcAAPaZFJSvFwAARSup4q8XAAAy32bOsBcAAIFw+xyxFwAA0AGQa7EXAAAfkyS6sRcAAG4kuQiy"
    "FwAAW9h29LIXAACqaQtDsxcAAPn6n5GzFwAASIw04LMXAACXHckutBcAAITRhhq1FwAA02IbabUXAAAi9K+3tRcAAHGFRAa2"
    "FwAAwBbZVLYXlHSUYn2UaD9oQksBiWhHh5RSlHOHlGJoUE51hpRSlGF9lGhvfZQoaHFoi2hyXZR9lChodWiPaHZoeUsATSwB"
    "SwGHlFKUdWF1c3SUYmh9aH5of2iAaIJ9lGiEfZRohohzaIFOdWKMB3N1bW1hcnmUfZQojAxtZWFuX21vbnRobHmUR7+2ku8B"
    "UubejAZzaGFycGWUR8AiCtX7RdGIjAxtYXhfZHJhd2Rvd26UR7/n1c9Jv2f1jBN0dXJub3Zlcl9hbm51YWxpemVklEc/+uFH"
    "rhR64owSYXZnX2dyb3NzX2V4cG9zdXJllEc//+SxfksX5XV1jApuZXh0X2Nsb3NllH2UKGgDaAYpgZR9lChoCWgMKYGUKF2U"
    "aBFoE32UKGgVaB1oUE51hpRSlGFdlGgsaC5LAIWUaDCHlFKUKEsBTSwBhZRoWolCYAkAAAAAAAAAAAAA4IKmG0uMg78wlmOm"
    "cvCUvwBW9/Z4JkK/4OU/A7x2h7/g9QVBxRSWv8BXZ5OnVns/wFRoy6LCkL8gUrTBPjWEv0Ds7HZHOYi/wM5SQIGndj8A00nA"
    "hxZXv4BpgZoXsnq/4KZhCcEijL+AHHcQuhBvPyAFi79JEY2/AO3hRy0feb+AmHfOKeJjv+Am04BqR4O/AFMI80LZYb8APl6n"
    "PEGQvwDII2sXAja/ANq/vxgATj+AuQoZK3uBv4BI7FBXyWW/YJ+7Xp9whL+Ac0UhUaCDvxA+xjstTJG/IHYZCPCejr8Aqts/"
    "QP5rvyDnjJpm7IS/wBxPX/xaej+gCqpirIiXvyCded3iy4G/QJrJrMuzeb+AHY5uraBoP4BKCoFIg3+/wOid7+p6gr+ApwUO"
    "Q1ZqPwCKLVAaDV4/QHGFNMNegL+AnWZj7S90v7A1UJ4AcpS/YFK0foJsjD+AmBUX1lBwP4BEA/7XLoW/ALJsIxr+QL+AWe42"
    "CIt3P4AMIUoeeIO/AJKCGAIfWb+AF7WS/4xjP8C8T30Q1oK/IGMTVR/Oir/A5bKNtxh+vwDT7012bW2/ANJqgCiZdj8AcJUP"
    "7mZzvwC68hddKGU/gDPHNuPiY7+g3+hAJwuIvwDXvYyQZoe/AAj+WppVNz+A+23c3R1nv4COMybnMHO/oPsAIfhQjr9AbiYT"
    "Roh1v4B4SkiAymy/AGvYAx3TeL9gczpL9omCP8C8f3aDYX+/EOIPLHGfkL+AxUn5dTxlvwCro+VtMnu/AAy+Vm5PN7/AXx9t"
    "4byEvwDL5sL20Ha/0A+d923ulr8AtLOZjVZZvwCgjr1OMCg/gFMblS9qi7/APM4A8FJ+vwBXF3XPIHu/AFpgk9OcSD/A91Kk"
    "sDVyP8CwI26G9Xq/AF+FO4U3ir8A8GaDlc4tvwAI3QzvyHA/gCmg6Bbzfb+Aq9PmYZZlP4B1/lbb/mk/AJa4kvXcSr9A2k52"
    "R8V3vwBgsGFTjSY/gM0drEBai78AOCcQHtVYP4B8+/vvx3K/wNhsFxWPeb8AtE5EYfBSv+A2oy21yY+/AMRon5stOL8AUe9R"
    "0UNrPyCJ5L1sQIS/AICFmH/8Oz+ApAjxWnKJv8A7q/W6coc/wC+dEGHcgz9Aq9DWFbV9vyAcztkeFoa/AERHBEdfgb8g3Xwb"
    "tYSMv4BqvGUqYXy/ANPs1zvFeb9AxKCt2JCKv0Ca7TpqtHS/oEwRPtY/jr/g/DI744GDv+A6ddKlKpO/cGhYgkBpkD+gjwA6"
    "eE+Iv0CbVNVFSoe/QAkg3C1Jer8APsHfOF9GvwDA/H0lBn4/oEBgGI2Mg78Aj/msOdGBPwBNQ3v0EH8/YF6PFtQ7g79Abfpd"
    "mBlyv2ANzpdbJIe/APuI78uie79AU6DvXNWGv+ClAA8UBZK/AF7V/QEjUz8AtXYRraBiv4BmnNSyRGG/gLpcqfVFh7/AKiUh"
    "ToZ3vwCFitrhmF4/wLrZnz4Ocb+AdsSRuMKNv8C/fUqKYn2/IAPn7Yl0hL9gzX3t0B+MvzDe8GnN/pE/AAXWdHLSVj9A7VlX"
    "mQN5P8BSLZR87nK/AMClhP6eKj+ANMbVIEBkPwAMUIjCQGm/8LuJKiiUkb8AyEx/GlJVv0BjjL9IEXq/AIA7SUjzRz+A865N"
    "DXlpvwCSUA6P/E0/wFKDJylKfr8A+OVhMYB2P8AYmKjceYu/oAFWLpgoj79As7FCp0Fyv8BA4ZGJf3u/4PqrUp3mjL8AGASU"
    "SoVfvwDsxVpgEli/AOw9v9iEVD8ABmzqCepRv5CnN9Ej8p8/QHp6rJ6pg78ASpTt9lVNP8DFEXIYZ4m/AHXj8ooqhD8AQV+U"
    "l19cv8DeZKeqKn2/gJ3lpCWWh79AEyTjFhxwP6AmafIDXIG/wBtGFyevdb8AGMkEDDcpP4DxTYDT3mu/AIuPZgHxXL/AglZF"
    "6et1vwAGHS+VOnI/AMzLw44kR7+AvsBT5ytyv+ArgRHEfIa/gC6WwsN5eL8AuZ9IBRFavwAC10y4EV2/wH2qoxqLej8A4nmu"
    "ZcFUP4ArLltN1mK/gCwVIAAYb7/AuuTGkbCCv4CSJFA5tmK/AObwMBg4Ub8A6GEnm2QyP0DcBOuGHHU/AGeh9KK6Xr+Awk8z"
    "XrWMvwBCFwAsQW2/YJXJXNAfgr+g9R0iWkiMP4CRs3sovnq/4BFoq17blL/AFtJw1iKDv8C/Jc6KJHW/4MsxLC92kb/ABWbW"
    "9q5wP6DYeIQoMpK/oEYWv1InhL8AoYOypaFXvyAG6ohPgZC/4FtEUseyj78AzBW9xXZGP4BdQ9GB23W/AGfkXlyjdr+APATd"
    "0ox1P4DWTVPcg4O/ABaWyfh0Uj9gjInCp02FP4B65F3GFmw/4GPjyXjLg7/gzjg+ojyGvwAIDL8Wrke/ALpP/BH1UL8ASTFU"
    "qRFwv4DT7IIiHWG/AESy/13nR78AspgZURxavwBJqx+GjFw/ACCFHjyORr8AwFODB04Sv+BlIDb6S4i/oMUxiOybjL+ArrPX"
    "2XeavwBOpuKZU2U/UCitN8w1mL8A7UrJXSBYvwBx45HZt4+/EOYvFyYrk78AmcrKai53vyDezRubgYy/QBhAW8NOhb8AAKiW"
    "fiVZPwAL2hnJjXe/wP99+WrZdL9AjVNdNfd8P2Bs+QIG9Yu/AI+Gh06Rgb8ALKuf4CJpv7A5uHRyCZO/QO7mdTvgdj8QxMMl"
    "N8mRv6BB2DuUfIS/wOOM/xqdfj8AFhOagNRovwCda37aHVC/gFBoMNWoaz+Aa9P2Uthwv0Dr5naO3IG/QNx5tkiOeb9ge2iV"
    "1M+Iv8BDQZxhI36/APKmoaxBdb+AetNb0e5uvwC/8ekkSIO/QHxk8QO/c7/wmWhWSMeRv8BTksg3EYa/APz92Dx5cj8Aiv8y"
    "DTtdvwBlogyPfVU/wI1l1LO8fb9ASJEpdCt3vwDQ014MLhO/wJ+d05w9jz+AHakzBbZvPwDLjgK0Nnc/AAlIdgJSeD+ARBDR"
    "+oCGv8BzAIXg+Ya/AE8bP+/Kej8AnOjTxFtDPwCy9xzIGkE/AExCYEbyQj/gTtTg6YiBv4DYq6CU4Ii/QD3e0zu5gD9AhNiR"
    "Ftd2P0BUKjVMmnG/AEMF0iS1jT/g00FDQGmDv4BM455Y/2y/ANqHDK3FQj8A25fjMV5zvwCuZn3ypVU/AFVmMaeAdr8AJh28"
    "lJZMP5R0lGJhXZRoEWgTfZQoaBVoGGgbSh8G8QROh5RSlGgjaCxoLksAhZRoMIeUUpQoSwFNLAGFlGg2iUJgCQAAAAARZdhU"
    "NhcAAGD2bKM2FwAAr4cB8jYXAAD+GJZANxcAAE2qKo83FwAAOl7oejgXAACJ73zJOBcAANiAERg5FwAAJxKmZjkXAAB2ozq1"
    "ORcAAGNX+KA6FwAAsuiM7zoXAAABeiE+OxcAAFALtow7FwAAn5xK2zsXAACMUAjHPBcAANvhnBU9FwAAKnMxZD0XAAB5BMay"
    "PRcAAMiVWgE+FwAAtUkY7T4XAAAE26w7PxcAAFNsQYo/FwAAov3V2D8XAADxjmonQBcAAN5CKBNBFwAALdS8YUEXAAB8ZVGw"
    "QRcAAMv25f5BFwAAGoh6TUIXAAAHPDg5QxcAAFbNzIdDFwAApV5h1kMXAAD07/UkRBcAAEOBinNEFwAAMDVIX0UXAAB/xtyt"
    "RRcAAM5XcfxFFwAAHekFS0YXAABsepqZRhcAAFkuWIVHFwAAqL/s00cXAAD3UIEiSBcAAEbiFXFIFwAAlXOqv0gXAACCJ2ir"
    "SRcAANG4/PlJFwAAIEqRSEoXAABv2yWXShcAAL5suuVKFwAAqyB40UsXAAD6sQwgTBcAAElDoW5MFwAAmNQ1vUwXAADnZcoL"
    "TRcAANQZiPdNFwAAI6scRk4XAAByPLGUThcAAMHNReNOFwAAEF/aMU8XAAD9EpgdUBcAAEykLGxQFwAAmzXBulAXAADqxlUJ"
    "URcAADlY6ldRFwAAJgyoQ1IXAAB1nTySUhcAAMQu0eBSFwAAE8BlL1MXAABiUfp9UxcAAE8FuGlUFwAAnpZMuFQXAADtJ+EG"
    "VRcAADy5dVVVFwAAi0oKpFUXAAB4/sePVhcAAMePXN5WFwAAFiHxLFcXAABlsoV7VxcAALRDGspXFwAAoffXtVgXAADwiGwE"
    "WRcAAD8aAVNZFwAAjquVoVkXAADdPCrwWRcAAMrw59taFwAAGYJ8KlsXAABoExF5WxcAALekpcdbFwAABjY6FlwXAADz6fcB"
    "XRcAAEJ7jFBdFwAAkQwhn10XAADgnbXtXRcAAC8vSjxeFwAAHOMHKF8XAABrdJx2XxcAALoFMcVfFwAACZfFE2AXAABYKFpi"
    "YBcAAEXcF05hFwAAlG2snGEXAADj/kDrYRcAADKQ1TliFwAAgSFqiGIXAABu1Sd0YxcAAL1mvMJjFwAADPhQEWQXAABbieVf"
    "ZBcAAKoaeq5kFwAAl843mmUXAADmX8zoZRcAADXxYDdmFwAAhIL1hWYXAADTE4rUZhcAAMDHR8BnFwAAD1ncDmgXAABe6nBd"
    "aBcAAK17BaxoFwAA/Aya+mgXAADpwFfmaRcAADhS7DRqFwAAh+OAg2oXAADWdBXSahcAACUGqiBrFwAAErpnDGwXAABhS/xa"
    "bBcAALDckKlsFwAA/20l+GwXAABO/7lGbRcAADuzdzJuFwAAikQMgW4XAADZ1aDPbhcAAChnNR5vFwAAd/jJbG8XAABkrIdY"
    "cBcAALM9HKdwFwAAAs+w9XAXAABRYEVEcRcAAKDx2ZJxFwAAjaWXfnIXAADcNizNchcAACvIwBtzFwAAellVanMXAADJ6um4"
    "cxcAALaep6R0FwAABTA883QXAABUwdBBdRcAAKNSZZB1FwAA8uP53nUXAADfl7fKdhcAAC4pTBl3FwAAfbrgZ3cXAADMS3W2"
    "dxcAABvdCQV4FwAACJHH8HgXAABXIlw/eRcAAKaz8I15FwAA9USF3HkXAABE1hkrehcAADGK1xZ7FwAAgBtsZXsXAADPrAC0"
    "excAAB4+lQJ8FwAAbc8pUXwXAABag+c8fRcAAKkUfIt9FwAA+KUQ2n0XAABHN6UofhcAAJbIOXd+FwAAg3z3Yn8XAADSDYyx"
    "fxcAACGfIACAFwAAcDC1ToAXAAC/wUmdgBcAAKx1B4mBFwAA+wac14EXAABKmDAmghcAAJkpxXSCFwAA6LpZw4IXAADVbhev"
    "gxcAACQArP2DFwAAc5FATIQXAADCItWahBcAABG0aemEFwAA/mcn1YUXAABN+bsjhhcAAJyKUHKGFwAA6xvlwIYXAAA6rXkP"
    "hxcAACdhN/uHFwAAdvLLSYgXAADFg2CYiBcAABQV9eaIFwAAY6aJNYkXAABQWkchihcAAJ/r22+KFwAA7nxwvooXAAA9DgUN"
    "ixcAAIyfmVuLFwAAeVNXR4wXAADI5OuVjBcAABd2gOSMFwAAZgcVM40XAAC1mKmBjRcAAKJMZ22OFwAA8d37u44XAABAb5AK"
    "jxcAAI8AJVmPFwAA3pG5p48XAADLRXeTkBcAABrXC+KQFwAAaWigMJEXAAC4+TR/kRcAAAeLyc2RFwAA9D6HuZIXAABD0BsI"
    "kxcAAJJhsFaTFwAA4fJEpZMXAAAwhNnzkxcAAB04l9+UFwAAbMkrLpUXAAC7WsB8lRcAAArsVMuVFwAAWX3pGZYXAABGMacF"
    "lxcAAJXCO1SXFwAA5FPQopcXAAAz5WTxlxcAAIJ2+T+YFwAAbyq3K5kXAAC+u0t6mRcAAA1N4MiZFwAAXN50F5oXAACrbwlm"
    "mhcAAJgjx1GbFwAA57RboJsXAAA2RvDumxcAAIXXhD2cFwAA1GgZjJwXAADBHNd3nRcAABCua8adFwAAXz8AFZ4XAACu0JRj"
    "nhcAAP1hKbKeFwAA6hXnnZ8XAAA5p3vsnxcAAIg4EDugFwAA18mkiaAXAAAmWznYoBcAABMP98OhFwAAYqCLEqIXAACxMSBh"
    "ohcAAADDtK+iFwAAT1RJ/qIXAAA8CAfqoxcAAIuZmzikFwAA2iowh6QXAAApvMTVpBcAAHhNWSSlFwAAZQEXEKYXAAC0kqte"
    "phcAAAMkQK2mFwAAUrXU+6YXAAChRmlKpxcAAI76JjaoFwAA3Yu7hKgXAAAsHVDTqBcAAHuu5CGpFwAAyj95cKkXAAC38zZc"
    "qhcAAAaFy6qqFwAAVRZg+aoXAACkp/RHqxcAAPM4iZarFwAA4OxGgqwXAAAvftvQrBcAAH4PcB+tFwAAzaAEbq0XAAAcMpm8"
    "rRcAAAnmVqiuFwAAWHfr9q4XAACnCIBFrxcAAPaZFJSvFwAARSup4q8XAAAy32bOsBcAAIFw+xyxFwAA0AGQa7EXAAAfkyS6"
    "sRcAAG4kuQiyFwAAW9h29LIXAACqaQtDsxcAAPn6n5GzFwAASIw04LMXAACXHckutBcAAITRhhq1FwAA02IbabUXAAAi9K+3"
    "tRcAAHGFRAa2FwAAwBbZVLYXlHSUYn2UaD9oQksBiWhHh5RSlHOHlGJoUE51hpRSlGF9lGhvfZQoaHFouGhyXZR9lChodWi/"
    "aHZoeUsATSwBSwGHlFKUdWF1c3SUYmh9aH5of2iAaIJ9lGiEfZRohohzaIFOdWJoh2gGKYGUfZQoaAloDCmBlChdlGi7YV2U"
    "aCxoLksAhZRoMIeUUpQoSwFNLAGFlGhaiUJgCQAAAAAAAABq+EAZ3skbWC74QAq9gdHCr/dAZfaL+2as90Dcsyz492b3QINE"
    "dB/I5fZAlE0O5OcM90Djh3CoUqz2QLVVS/IMc/ZAnWgtDxMv9kA+7u0HfE72QDLfD/lvRvZAgBehkkUh9kCAkrv7cNP1QMEp"
    "0Dmh6PVAXq4QmQaZ9UAqUSVpHXf1QLUPZPrGafVAwxX5mSw29UBqAIjOVyr1QK9ESj5V1PRAf3Rm04rS9EDrq/YvbNf0QKk7"
    "qonhqfRAxxw1CtCb9EArOC5iKGf0QEALNIQaNfRAH/sG/rfd80Ax2wzdrZHzQOXku3aPgPNAEflqxY1N80AxsoGQWW3zQANb"
    "YAIN+/JAoYoPytPQ8kC9vF0PmrLyQL+5QeX9wPJAxg47GA6c8kCjlisKEXHyQMp1hp4+gPJA7cOIhe6I8kAurEcbAWPyQI6X"
    "RUbOS/JAokeby0nu8UAvUEQD/y3yQEgShNuIQPJA6AJnlDQQ8kAY1fuxzg3yQDw8VGxfKPJA8fRb5y788UA7GEyuH/XxQGvY"
    "8VgYAPJAZ0eEerbV8UCreYFk9JnxQGCzaYnYePFAT2vzQMdo8UCyw+/4XYHxQGKxK7wjbPFAASt7rah38UBxJTbIzWzxQN7C"
    "whNvOPFAW/O6DRAG8UBlNnNKnQfxQPJCbexP+/BAb94/lvHm8ECFlJ965KbwQP56Opt7kPBA4gmfXJSB8EBrwVAz+GfwQKX8"
    "VQ/9jfBA0PU0EIVt8EDD+L8pQCnwQKqLt46GHvBAe+mKPSAD8EA4qsf9qgHwQDFZI9BZsO9AkC5cdymD70AWk9O0gc7uQISz"
    "gWBPwu5ACKgsY8PD7kAujOVWVlruQBmKu57PIO5AMXYbeLrt7UCmlEW2e/PtQI1apiKSFe5AXJocbuHi7UAeqe6n8IDtQBS6"
    "zvI4f+1AeH29miqe7UBu3/XwuWbtQMASd4aPeu1AIkV6DYKS7UByroM+TYztQFWsCTxnYO1AZ2pOfLJh7UB5NU1JPf3sQC+w"
    "tsh8CO1A1txMb2jm7EAb2cD6PbjsQIcBxEq+r+xAV1wpAMI97EAPRPMtFzvsQJzJ5N0kU+xAXleQ53AL7ED2SbbFgQ7sQKSn"
    "gmJDtetAAVrH4nkG7EBZiWJKDUzsQJihVS+DF+xAeLaV2fTJ60Dwhly8nI3rQP94bAdkK+tAvGVSGTP76kDtQav/vc/qQBxq"
    "oWS1dupANgu3mnZU6kA5Lq3D5/DpQE+Zz2+mselABvjApog26UA3OX03+p3pQDV51M8hUOlAEg9wbHAG6UBlg6SAU93oQPoh"
    "+vb62OhAn78gWZsH6UAhJJyJccroQNMpcRaoAelAxqTeyzUy6UA7FdQdovXoQIYZ9dll2ehAFLZX5oOR6EBmfEVdFGfoQDlv"
    "ShFuIehAC2Mx/7i050CcKa+dz7vnQGsUfM3+redADkgMiDeh50AVq0hkeVznQPalPF0gOudA4OFsGDtF50Asd/rRbCznQBhi"
    "jrs31uZATyAT0Uas5kDEHR3XTXLmQDZTiIFkI+ZA/yz9JP2G5kBOGDqfBY/mQCq/BitKsuZASCfPSm+X5kB0Rmz/m5jmQLx4"
    "U6nopuZAVXwJbAiV5kAAPESbyjHmQO9SzctlKuZADtaN9EgG5kCsagjyZwrmQCONUHDc+OVA1HfCLAL+5UD2RlP5X9TlQEXb"
    "qeMS8+VASLEAKrCn5UB0nP18WFPlQB+z6jcDO+VA+u2HZ4YW5UDNd9GqV8rkQL+AolsawORALyR7XEy45EAwdaH28L7kQIcV"
    "SGEiueRAI9jppaNe5UDh4STKHSrlQDmwsIv3LuVAlQ6uyLPr5EBhqfBKcCDlQHStn4sSF+VAtCKAfKDw5EDQj9Cs47LkQIOg"
    "J+e6x+RA+HjWdqOa5ECrtJfytn7kQHZdnla5f+RABiCr1N5t5EDrhwDVoWTkQNU5PhGxSORAnCkUHc1f5EDgzY0UHlzkQLJR"
    "yZT+RORAvm5/ugQM5ECwpT0jWu3jQH077mk85eNApz5fCDPc40D+K1mFJf3jQIL7OQihA+RAM7H+9Nj340CpndrgceTjQDBA"
    "XNT4teNA0RMgOnKq40C+uzW3J6XjQM4lbAyRpuNAr+z9s37A40Aikt7eArfjQLy/DGBDcONAT246DH5e40B9B/1pnDLjQKL1"
    "Oi17duNAhA/cVPNV40Bp9cgoIfHiQInSff3Rw+JAaup9Hgar4kAyBiCzh1niQBBLjeOpbOJAbOEg3tkY4kB+dyDJQuvhQIOq"
    "5/qk5OFACkFr9c+a4UCgLmGkDlXhQPNxFVgZWOFAAcw9xGdA4UCEMtYR/yfhQIBor5AaP+FAo9VJbQgV4UBDJy+Q9RnhQH7w"
    "QrV/R+FACnFGkapW4UCNtju/wyvhQBvvdUAJ/OBABRsr3eT44EChq2KmZfTgQDCfoYle4+BAeSckX1ba4EAV4jatMNfgQCki"
    "9M1R0OBArKyt3NHX4ECIv0UN2tTgQLJKGgeN1OBAPcP2iG+h4EC96xBf9mXgQJZla47o8t9Aet9btxkE4EAB2xVqU0bfQBTP"
    "zzmJOt9AU3i/ubi+3kBZSkUlYyveQPjYpECt/91A+uXWYciU3UA3WtiW/kXdQA0sqRR/Ud1Ad2dMH1Ym3UDButAYWgDdQA1b"
    "pczaNN1AyHGT4cnO3EB0ycA1h4/cQFPtI/MXedxA9R0xgpXx20BjAcpNiRncQJR2oz+XnNtALIi8yuFV20BiZ/A6L4rbQED2"
    "XbXQdNtAhemFsuZt20CZueQknIXbQKeQTm6iaNtAm66Yb3Ar20CcGuvyCgDbQDeofWNNrNpADcHAVg962kBA7hR14lbaQKPX"
    "P25sPdpA8mHW6i3+2UCRj6PDGd7ZQAm41Rgha9lA1UztyAMl2UBYyLv0C0LZQMNSOLmCNtlASDHvEvo+2UDi0PItDhDZQNUk"
    "dQjD69hAsmeyiUvr2EDWXgc5m0zZQGBCNletZdlAK5RIVYaK2UCEF6cIWbHZQM81uRgTadlA9EuedBgg2UAPFENJK0rZQJwq"
    "Tm3+TdlAw/R/FGBR2UA0CMhxH1XZQE2NSAOZHdlAhF3mKH/P2EDRFyCfXAPZQH4e8H4RJ9lAh7KDbGUL2UAZi0jRZWjZQAda"
    "Jpm/KtlAVAcnX/ET2UD6TbHnnhfZQFJW+yE/+dhAAKboq7EB2UBFA8BEht7YQJU9yjMU5NhAlHSUYmFdlGgRaBN9lChoFWgY"
    "aBtKHwbxBE6HlFKUaCNoLGguSwCFlGgwh5RSlChLAU0sAYWUaDaJQmAJAAAAABFl2FQ2FwAAYPZsozYXAACvhwHyNhcAAP4Y"
    "lkA3FwAATaoqjzcXAAA6Xuh6OBcAAInvfMk4FwAA2IARGDkXAAAnEqZmORcAAHajOrU5FwAAY1f4oDoXAACy6IzvOhcAAAF6"
    "IT47FwAAUAu2jDsXAACfnErbOxcAAIxQCMc8FwAA2+GcFT0XAAAqczFkPRcAAHkExrI9FwAAyJVaAT4XAAC1SRjtPhcAAATb"
    "rDs/FwAAU2xBij8XAACi/dXYPxcAAPGOaidAFwAA3kIoE0EXAAAt1LxhQRcAAHxlUbBBFwAAy/bl/kEXAAAaiHpNQhcAAAc8"
    "ODlDFwAAVs3Mh0MXAAClXmHWQxcAAPTv9SREFwAAQ4GKc0QXAAAwNUhfRRcAAH/G3K1FFwAAzldx/EUXAAAd6QVLRhcAAGx6"
    "mplGFwAAWS5YhUcXAACov+zTRxcAAPdQgSJIFwAARuIVcUgXAACVc6q/SBcAAIInaKtJFwAA0bj8+UkXAAAgSpFIShcAAG/b"
    "JZdKFwAAvmy65UoXAACrIHjRSxcAAPqxDCBMFwAASUOhbkwXAACY1DW9TBcAAOdlygtNFwAA1BmI900XAAAjqxxGThcAAHI8"
    "sZROFwAAwc1F404XAAAQX9oxTxcAAP0SmB1QFwAATKQsbFAXAACbNcG6UBcAAOrGVQlRFwAAOVjqV1EXAAAmDKhDUhcAAHWd"
    "PJJSFwAAxC7R4FIXAAATwGUvUxcAAGJR+n1TFwAATwW4aVQXAACelky4VBcAAO0n4QZVFwAAPLl1VVUXAACLSgqkVRcAAHj+"
    "x49WFwAAx49c3lYXAAAWIfEsVxcAAGWyhXtXFwAAtEMaylcXAACh99e1WBcAAPCIbARZFwAAPxoBU1kXAACOq5WhWRcAAN08"
    "KvBZFwAAyvDn21oXAAAZgnwqWxcAAGgTEXlbFwAAt6Slx1sXAAAGNjoWXBcAAPPp9wFdFwAAQnuMUF0XAACRDCGfXRcAAOCd"
    "te1dFwAALy9KPF4XAAAc4wcoXxcAAGt0nHZfFwAAugUxxV8XAAAJl8UTYBcAAFgoWmJgFwAARdwXTmEXAACUbaycYRcAAOP+"
    "QOthFwAAMpDVOWIXAACBIWqIYhcAAG7VJ3RjFwAAvWa8wmMXAAAM+FARZBcAAFuJ5V9kFwAAqhp6rmQXAACXzjeaZRcAAOZf"
    "zOhlFwAANfFgN2YXAACEgvWFZhcAANMTitRmFwAAwMdHwGcXAAAPWdwOaBcAAF7qcF1oFwAArXsFrGgXAAD8DJr6aBcAAOnA"
    "V+ZpFwAAOFLsNGoXAACH44CDahcAANZ0FdJqFwAAJQaqIGsXAAASumcMbBcAAGFL/FpsFwAAsNyQqWwXAAD/bSX4bBcAAE7/"
    "uUZtFwAAO7N3Mm4XAACKRAyBbhcAANnVoM9uFwAAKGc1Hm8XAAB3+MlsbxcAAGSsh1hwFwAAsz0cp3AXAAACz7D1cBcAAFFg"
    "RURxFwAAoPHZknEXAACNpZd+chcAANw2LM1yFwAAK8jAG3MXAAB6WVVqcxcAAMnq6bhzFwAAtp6npHQXAAAFMDzzdBcAAFTB"
    "0EF1FwAAo1JlkHUXAADy4/nedRcAAN+Xt8p2FwAALilMGXcXAAB9uuBndxcAAMxLdbZ3FwAAG90JBXgXAAAIkcfweBcAAFci"
    "XD95FwAAprPwjXkXAAD1RIXceRcAAETWGSt6FwAAMYrXFnsXAACAG2xlexcAAM+sALR7FwAAHj6VAnwXAABtzylRfBcAAFqD"
    "5zx9FwAAqRR8i30XAAD4pRDafRcAAEc3pSh+FwAAlsg5d34XAACDfPdifxcAANINjLF/FwAAIZ8gAIAXAABwMLVOgBcAAL/B"
    "SZ2AFwAArHUHiYEXAAD7BpzXgRcAAEqYMCaCFwAAmSnFdIIXAADoulnDghcAANVuF6+DFwAAJACs/YMXAABzkUBMhBcAAMIi"
    "1ZqEFwAAEbRp6YQXAAD+ZyfVhRcAAE35uyOGFwAAnIpQcoYXAADrG+XAhhcAADqteQ+HFwAAJ2E3+4cXAAB28stJiBcAAMWD"
    "YJiIFwAAFBX15ogXAABjpok1iRcAAFBaRyGKFwAAn+vbb4oXAADufHC+ihcAAD0OBQ2LFwAAjJ+ZW4sXAAB5U1dHjBcAAMjk"
    "65WMFwAAF3aA5IwXAABmBxUzjRcAALWYqYGNFwAAokxnbY4XAADx3fu7jhcAAEBvkAqPFwAAjwAlWY8XAADekbmnjxcAAMtF"
    "d5OQFwAAGtcL4pAXAABpaKAwkRcAALj5NH+RFwAAB4vJzZEXAAD0Poe5khcAAEPQGwiTFwAAkmGwVpMXAADh8kSlkxcAADCE"
    "2fOTFwAAHTiX35QXAABsySsulRcAALtawHyVFwAACuxUy5UXAABZfekZlhcAAEYxpwWXFwAAlcI7VJcXAADkU9CilxcAADPl"
    "ZPGXFwAAgnb5P5gXAABvKrcrmRcAAL67S3qZFwAADU3gyJkXAABc3nQXmhcAAKtvCWaaFwAAmCPHUZsXAADntFugmxcAADZG"
    "8O6bFwAAhdeEPZwXAADUaBmMnBcAAMEc13edFwAAEK5rxp0XAABfPwAVnhcAAK7QlGOeFwAA/WEpsp4XAADqFeednxcAADmn"
    "e+yfFwAAiDgQO6AXAADXyaSJoBcAACZbOdigFwAAEw/3w6EXAABioIsSohcAALExIGGiFwAAAMO0r6IXAABPVEn+ohcAADwI"
    "B+qjFwAAi5mbOKQXAADaKjCHpBcAACm8xNWkFwAAeE1ZJKUXAABlARcQphcAALSSq16mFwAAAyRAraYXAABStdT7phcAAKFG"
    "aUqnFwAAjvomNqgXAADdi7uEqBcAACwdUNOoFwAAe67kIakXAADKP3lwqRcAALfzNlyqFwAABoXLqqoXAABVFmD5qhcAAKSn"
    "9EerFwAA8ziJlqsXAADg7EaCrBcAAC9+29CsFwAAfg9wH60XAADNoARurRcAABwymbytFwAACeZWqK4XAABYd+v2rhcAAKcI"
    "gEWvFwAA9pkUlK8XAABFK6nirxcAADLfZs6wFwAAgXD7HLEXAADQAZBrsRcAAB+TJLqxFwAAbiS5CLIXAABb2Hb0shcAAKpp"
    "C0OzFwAA+fqfkbMXAABIjDTgsxcAAJcdyS60FwAAhNGGGrUXAADTYhtptRcAACL0r7e1FwAAcYVEBrYXAADAFtlUtheUdJRi"
    "fZRoP2hCSwGJaEeHlFKUc4eUYmhQTnWGlFKUYX2UaG99lChocWjfaHJdlH2UKGh1aONodmh5SwBNLAFLAYeUUpR1YXVzdJRi"
    "aH1ofmh/aIBogn2UaIR9lGiGiHNogU51YmisfZQoaK5Hv7aS7wFS5tZor0fAIhZZBWOcXWiwR7/n3r3WlM+UaLFHP/rhR64U"
    "euJoskc//+SxfksX5XV1dS4="
)


# ───── (a) default off: byte-identical to the pre-change engine ───────────
def test_a_default_off():
    print("\n[a] delist_exit=False (default) is byte-identical to pre-change engine")
    idx, close, opn, w, lq = build_panel()

    cfg = BTConfigV2()
    check("BTConfigV2 defaults off",
          cfg.delist_exit is False and cfg.delist_haircut_pct == 0.0)

    runs = {
        "next_open": run_backtest_v2(w, close, BTConfigV2(exec_model="next_open"),
                                     open_prices=opn),
        "next_close": run_backtest_v2(w, close, BTConfigV2(exec_model="next_close")),
    }

    check("pristine capture embedded", PRISTINE_B64 is not None)
    pristine = pickle.loads(base64.b64decode(PRISTINE_B64))
    for model, bt in runs.items():
        p = pristine[model]
        check(f"{model}: returns byte-identical to pre-change engine",
              np.array_equal(bt["returns"].to_numpy(), p["returns"].to_numpy())
              and bt["returns"].index.equals(p["returns"].index))
        check(f"{model}: equity byte-identical",
              np.array_equal(bt["equity"].to_numpy(), p["equity"].to_numpy()))
        for k, v in p["summary"].items():
            check(f"{model}: summary[{k}] exact", bt["summary"][k] == v,
                  f"new={bt['summary'][k]!r} pristine={v!r}")
        check(f"{model}: no delist keys added to default summary",
              "delist_exit" not in bt["summary"]
              and "n_delist_exits" not in bt["summary"])

    # last_quote passed but hook off → ignored, byte-identical.
    bt_lq = run_backtest_v2(w, close, BTConfigV2(exec_model="next_close"),
                            last_quote=lq)
    check("last_quote ignored when delist_exit=False (byte-identical)",
          np.array_equal(bt_lq["returns"].to_numpy(),
                         runs["next_close"]["returns"].to_numpy())
          and np.array_equal(bt_lq["equity"].to_numpy(),
                             runs["next_close"]["equity"].to_numpy()))

    # Pin the documented silent behavior: dead name holds weight at 0 return.
    eff = runs["next_close"]["weights"]
    check("silent: dead BANKR keeps 0.5 effective weight forever",
          bool((eff["BANKR"].iloc[BANKR_LAST + 1:] == 0.5).all()))
    check("silent: gross stays 2.0 after death (cap still deflated)",
          np.isclose(eff.abs().sum(axis=1).iloc[-1], 2.0))

    # Guard rails: misuse raises instead of silently no-opping.
    try:
        run_backtest_v2(w, close, BTConfigV2(delist_exit=True))
        check("delist_exit without last_quote raises", False)
    except ValueError:
        check("delist_exit without last_quote raises", True)
    try:
        run_backtest_v2(w, close,
                        BTConfigV2(delist_exit=True, exec_model="legacy_period"),
                        last_quote=lq)
        check("delist_exit under legacy_period raises", False)
    except ValueError:
        check("delist_exit under legacy_period raises", True)


# ───── (b) hook on: exit at last quoted close, tc charged, gross freed ────
def test_b_hook_on():
    print("\n[b] delist_exit=True: exit at last quoted close, tc, gross freed")
    idx, close, opn, w, lq = build_panel()
    cfg0 = BTConfigV2(exec_model="next_close", tc_bps=0.0, delist_exit=True)
    bt = run_backtest_v2(w, close, cfg0, last_quote=lq)
    eff, r = bt["weights"], bt["returns"]
    exit_day = idx[BANKR_LAST + 1]

    # Held through the last quoted close, zero from the day after — forever,
    # even past the day-285 re-assertion of 0.6 by the naive selector.
    check("held at last quoted close (eff 0.5 on lq day)",
          eff.at[idx[BANKR_LAST], "BANKR"] == 0.5)
    check("eff = 0 from day after last quote, permanently",
          bool((eff["BANKR"].loc[exit_day:] == 0.0).all()))
    check("ACQ exits one day after ITS last quote",
          eff.at[idx[ACQ_LAST], "ACQ"] > 0.0
          and bool((eff["ACQ"].loc[idx[ACQ_LAST + 1]:] == 0.0).all()))

    # Gross frees up: cap (2.0 < 2.4) deflated all names to 0.5; after BANKR
    # dies gross target = 1.8 → survivors rise to their full 0.6.
    check("gross freed for survivors on exit day",
          eff.at[exit_day, "LIVE1"] == 0.6 and eff.at[exit_day, "LIVE2"] == 0.6
          and eff.at[exit_day, "ACQ"] == 0.6)
    check("exit trade in turnover (Δ BANKR = -0.5 on exit day)",
          np.isclose(eff.diff().at[exit_day, "BANKR"], -0.5))

    # tc charged on the exit turnover like any sell:
    # |Δ| on exit day = 0.5 (BANKR out) + 3×0.1 (cap release) = 0.8.
    bt_tc = run_backtest_v2(
        w, close, BTConfigV2(exec_model="next_close", tc_bps=100.0,
                             delist_exit=True), last_quote=lq)
    tc_paid = r.loc[exit_day] - bt_tc["returns"].loc[exit_day]
    check("tc charged on exit-day turnover 0.8 @100bp",
          np.isclose(tc_paid, 0.8 * 100.0 / 10_000.0, atol=1e-12),
          f"got {tc_paid:.6e}")

    # Returns identical to the DEFAULT engine through the last quoted close
    # (the hook only changes the book from the day after).
    bt_def = run_backtest_v2(w, close, BTConfigV2(exec_model="next_close",
                                                  tc_bps=0.0))
    check("returns unchanged through last quoted close",
          np.array_equal(r.loc[:idx[BANKR_LAST]].to_numpy(),
                         bt_def["returns"].loc[:idx[BANKR_LAST]].to_numpy()))

    # Equivalence: hook == manually zeroing the daily weights from each
    # last-quote date onward (the mask composes exactly like apply_gate).
    manual = expand_daily(w, idx)
    manual.loc[idx[BANKR_LAST]:, "BANKR"] = 0.0
    manual.loc[idx[ACQ_LAST]:, "ACQ"] = 0.0
    bt_man = run_backtest_v2(manual, close,
                             BTConfigV2(exec_model="next_close", tc_bps=0.0),
                             weights_are_daily=True)
    check("hook == manual weight zeroing (byte-identical returns)",
          np.array_equal(r.to_numpy(), bt_man["returns"].to_numpy()))

    # Dead name cannot leak: garbage post-death prices change NOTHING with
    # the hook on (and provably would corrupt the default engine).
    close_g = close.copy()
    close_g.loc[idx[BANKR_LAST + 1]:, "BANKR"] = 1e6
    bt_g = run_backtest_v2(w, close_g, cfg0, last_quote=lq)
    check("subsequent returns unaffected by dead name (garbage-price test)",
          np.array_equal(r.to_numpy(), bt_g["returns"].to_numpy()))
    bt_g_def = run_backtest_v2(w, close_g, BTConfigV2(exec_model="next_close",
                                                      tc_bps=0.0))
    check("(control) default engine IS corrupted by the same garbage",
          not np.allclose(bt_def["returns"].to_numpy(),
                          bt_g_def["returns"].to_numpy()))

    # Provenance + next_open smoke (same effective book, finite returns).
    check("summary provenance: delist_exit / n_delist_exits",
          bt["summary"].get("delist_exit") is True
          and bt["summary"].get("n_delist_exits") == 2)
    bt_no = run_backtest_v2(w, close,
                            BTConfigV2(exec_model="next_open", tc_bps=0.0,
                                       delist_exit=True),
                            open_prices=opn, last_quote=lq)
    check("next_open: same effective book, finite returns",
          np.array_equal(bt_no["weights"].to_numpy(), eff.to_numpy())
          and np.isfinite(bt_no["returns"].to_numpy()).all()
          and bt_no["weights"].at[exit_day, "BANKR"] == 0.0)


# ───── (c) haircut arm: -30% on the bankruptcy exit day only ──────────────
def test_c_haircut():
    print("\n[c] delist_haircut_pct: -30% exactly on the bankruptcy exit day")
    idx, close, opn, w, lq = build_panel()
    kw = dict(exec_model="next_close", tc_bps=0.0, delist_exit=True)
    r0 = run_backtest_v2(w, close, BTConfigV2(**kw), last_quote=lq)["returns"]
    bt_h = run_backtest_v2(w, close,
                           BTConfigV2(delist_haircut_pct=0.30, **kw),
                           last_quote=lq)
    diff = bt_h["returns"] - r0

    bankr_exit = idx[BANKR_LAST + 1]
    acq_exit = idx[ACQ_LAST + 1]
    # BANKR terminal 4.0 < 20% of its 252d-ago close (~80.7) → bankruptcy
    # class; exited effective weight 0.5 → extra return −0.30 × 0.5 = −0.15.
    check("-0.30 × 0.5 exited weight hits the exit day",
          np.isclose(diff.loc[bankr_exit], -0.30 * 0.5, atol=1e-15),
          f"got {diff.loc[bankr_exit]:.6f}")
    check("haircut hits ONLY that day (all other days byte-identical)",
          np.array_equal(diff.drop(bankr_exit).to_numpy(),
                         np.zeros(len(diff) - 1)))
    # ACQ terminal 130 vs ~102.6 a year prior → NOT bankruptcy class.
    check("acquisition-class exit day NOT haircut",
          diff.loc[acq_exit] == 0.0, f"got {diff.loc[acq_exit]:.6e}")
    check("summary provenance: delist_haircut_pct",
          bt_h["summary"].get("delist_haircut_pct") == 0.30)


# ───── (d) fidelity chain: test_engine_v2.py as a script ──────────────────
def test_d_fidelity_chain():
    print("\n[d] fidelity chain: validation/test_engine_v2.py (script mode)")
    proc = subprocess.run(
        [sys.executable, str(ROOT / "validation" / "test_engine_v2.py")],
        capture_output=True, text=True, timeout=600, cwd=str(ROOT))
    ok = proc.returncode == 0 and "ALL TESTS PASSED" in proc.stdout
    if not ok:
        print(proc.stdout[-3000:])
        print(proc.stderr[-3000:])
    check("test_engine_v2.py → ALL TESTS PASSED", ok,
          f"rc={proc.returncode}")


if __name__ == "__main__":
    test_a_default_off()
    test_b_hook_on()
    test_c_haircut()
    test_d_fidelity_chain()
    print(f"\n{'ALL TESTS PASSED' if not FAILURES else f'{len(FAILURES)} FAILURES: {FAILURES}'}")
    sys.exit(0 if not FAILURES else 1)
